/*
 * RPCS3 PS5 - import self-check (generated by port/gen-import-check.sh from the linked title).
 *
 * The console leaves a title import pointing at nothing when no module gives it to titles.
 * rpcs3ps5_import_check() runs from the first constructor and writes every import that
 * resolved to NULL to /app0/rpcs3/ps5-boot.log, so one launch lists them all.
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
#include <stddef.h>

void rpcs3ps5_boot_log(const char *format, ...);

extern char rpcs3ps5_import_0 __asm__("_CurrentRuneLocale") __attribute__((weak));
extern char rpcs3ps5_import_1 __asm__("_DefaultRuneLocale") __attribute__((weak));
extern char rpcs3ps5_import_2 __asm__("_Exit") __attribute__((weak));
extern char rpcs3ps5_import_3 __asm__("_Unwind_Backtrace") __attribute__((weak));
extern char rpcs3ps5_import_4 __asm__("__cxa_atexit") __attribute__((weak));
extern char rpcs3ps5_import_5 __asm__("__error") __attribute__((weak));
extern char rpcs3ps5_import_6 __asm__("__fpclassifyd") __attribute__((weak));
extern char rpcs3ps5_import_7 __asm__("__inet_ntop") __attribute__((weak));
extern char rpcs3ps5_import_8 __asm__("__inet_pton") __attribute__((weak));
extern char rpcs3ps5_import_9 __asm__("__isfinite") __attribute__((weak));
extern char rpcs3ps5_import_10 __asm__("__isfinitef") __attribute__((weak));
extern char rpcs3ps5_import_11 __asm__("__isinf") __attribute__((weak));
extern char rpcs3ps5_import_12 __asm__("__isinff") __attribute__((weak));
extern char rpcs3ps5_import_13 __asm__("__isnormal") __attribute__((weak));
extern char rpcs3ps5_import_14 __asm__("__isnormalf") __attribute__((weak));
extern char rpcs3ps5_import_15 __asm__("__isthreaded") __attribute__((weak));
extern char rpcs3ps5_import_16 __asm__("__mb_cur_max") __attribute__((weak));
extern char rpcs3ps5_import_17 __asm__("__mb_sb_limit") __attribute__((weak));
extern char rpcs3ps5_import_18 __asm__("__stack_chk_fail") __attribute__((weak));
extern char rpcs3ps5_import_19 __asm__("__stack_chk_guard") __attribute__((weak));
extern char rpcs3ps5_import_20 __asm__("__stderrp") __attribute__((weak));
extern char rpcs3ps5_import_21 __asm__("__stdinp") __attribute__((weak));
extern char rpcs3ps5_import_22 __asm__("__stdoutp") __attribute__((weak));
extern char rpcs3ps5_import_23 __asm__("_exit") __attribute__((weak));
extern char rpcs3ps5_import_24 __asm__("_init_env") __attribute__((weak));
extern char rpcs3ps5_import_25 __asm__("_umtx_op") __attribute__((weak));
extern char rpcs3ps5_import_26 __asm__("abort") __attribute__((weak));
extern char rpcs3ps5_import_27 __asm__("accept") __attribute__((weak));
extern char rpcs3ps5_import_28 __asm__("acos") __attribute__((weak));
extern char rpcs3ps5_import_29 __asm__("acosf") __attribute__((weak));
extern char rpcs3ps5_import_30 __asm__("alarm") __attribute__((weak));
extern char rpcs3ps5_import_31 __asm__("asin") __attribute__((weak));
extern char rpcs3ps5_import_32 __asm__("asinf") __attribute__((weak));
extern char rpcs3ps5_import_33 __asm__("asprintf") __attribute__((weak));
extern char rpcs3ps5_import_34 __asm__("atan") __attribute__((weak));
extern char rpcs3ps5_import_35 __asm__("atan2") __attribute__((weak));
extern char rpcs3ps5_import_36 __asm__("atan2f") __attribute__((weak));
extern char rpcs3ps5_import_37 __asm__("atanf") __attribute__((weak));
extern char rpcs3ps5_import_38 __asm__("atexit") __attribute__((weak));
extern char rpcs3ps5_import_39 __asm__("atof") __attribute__((weak));
extern char rpcs3ps5_import_40 __asm__("atoi") __attribute__((weak));
extern char rpcs3ps5_import_41 __asm__("basename") __attribute__((weak));
extern char rpcs3ps5_import_42 __asm__("bind") __attribute__((weak));
extern char rpcs3ps5_import_43 __asm__("bsearch") __attribute__((weak));
extern char rpcs3ps5_import_44 __asm__("btowc") __attribute__((weak));
extern char rpcs3ps5_import_45 __asm__("calloc") __attribute__((weak));
extern char rpcs3ps5_import_46 __asm__("cbrt") __attribute__((weak));
extern char rpcs3ps5_import_47 __asm__("cbrtf") __attribute__((weak));
extern char rpcs3ps5_import_48 __asm__("ceil") __attribute__((weak));
extern char rpcs3ps5_import_49 __asm__("ceilf") __attribute__((weak));
extern char rpcs3ps5_import_50 __asm__("chdir") __attribute__((weak));
extern char rpcs3ps5_import_51 __asm__("chmod") __attribute__((weak));
extern char rpcs3ps5_import_52 __asm__("clock") __attribute__((weak));
extern char rpcs3ps5_import_53 __asm__("close") __attribute__((weak));
extern char rpcs3ps5_import_54 __asm__("connect") __attribute__((weak));
extern char rpcs3ps5_import_55 __asm__("copysign") __attribute__((weak));
extern char rpcs3ps5_import_56 __asm__("copysignf") __attribute__((weak));
extern char rpcs3ps5_import_57 __asm__("cos") __attribute__((weak));
extern char rpcs3ps5_import_58 __asm__("cosf") __attribute__((weak));
extern char rpcs3ps5_import_59 __asm__("cosh") __attribute__((weak));
extern char rpcs3ps5_import_60 __asm__("coshf") __attribute__((weak));
extern char rpcs3ps5_import_61 __asm__("ctime") __attribute__((weak));
extern char rpcs3ps5_import_62 __asm__("dirname") __attribute__((weak));
extern char rpcs3ps5_import_63 __asm__("dup") __attribute__((weak));
extern char rpcs3ps5_import_64 __asm__("dup2") __attribute__((weak));
extern char rpcs3ps5_import_65 __asm__("environ") __attribute__((weak));
extern char rpcs3ps5_import_66 __asm__("erf") __attribute__((weak));
extern char rpcs3ps5_import_67 __asm__("execv") __attribute__((weak));
extern char rpcs3ps5_import_68 __asm__("execve") __attribute__((weak));
extern char rpcs3ps5_import_69 __asm__("exit") __attribute__((weak));
extern char rpcs3ps5_import_70 __asm__("exp") __attribute__((weak));
extern char rpcs3ps5_import_71 __asm__("exp2") __attribute__((weak));
extern char rpcs3ps5_import_72 __asm__("exp2f") __attribute__((weak));
extern char rpcs3ps5_import_73 __asm__("exp2l") __attribute__((weak));
extern char rpcs3ps5_import_74 __asm__("expf") __attribute__((weak));
extern char rpcs3ps5_import_75 __asm__("expm1") __attribute__((weak));
extern char rpcs3ps5_import_76 __asm__("expm1f") __attribute__((weak));
extern char rpcs3ps5_import_77 __asm__("fabs") __attribute__((weak));
extern char rpcs3ps5_import_78 __asm__("fabsf") __attribute__((weak));
extern char rpcs3ps5_import_79 __asm__("fchmod") __attribute__((weak));
extern char rpcs3ps5_import_80 __asm__("fclose") __attribute__((weak));
extern char rpcs3ps5_import_81 __asm__("fcntl") __attribute__((weak));
extern char rpcs3ps5_import_82 __asm__("fdopen") __attribute__((weak));
extern char rpcs3ps5_import_83 __asm__("feof") __attribute__((weak));
extern char rpcs3ps5_import_84 __asm__("ferror") __attribute__((weak));
extern char rpcs3ps5_import_85 __asm__("fflush") __attribute__((weak));
extern char rpcs3ps5_import_86 __asm__("fgetc") __attribute__((weak));
extern char rpcs3ps5_import_87 __asm__("fgets") __attribute__((weak));
extern char rpcs3ps5_import_88 __asm__("fgetwc") __attribute__((weak));
extern char rpcs3ps5_import_89 __asm__("fileno") __attribute__((weak));
extern char rpcs3ps5_import_90 __asm__("flock") __attribute__((weak));
extern char rpcs3ps5_import_91 __asm__("floor") __attribute__((weak));
extern char rpcs3ps5_import_92 __asm__("floorf") __attribute__((weak));
extern char rpcs3ps5_import_93 __asm__("fma") __attribute__((weak));
extern char rpcs3ps5_import_94 __asm__("fmaf") __attribute__((weak));
extern char rpcs3ps5_import_95 __asm__("fmax") __attribute__((weak));
extern char rpcs3ps5_import_96 __asm__("fmaxf") __attribute__((weak));
extern char rpcs3ps5_import_97 __asm__("fmin") __attribute__((weak));
extern char rpcs3ps5_import_98 __asm__("fminf") __attribute__((weak));
extern char rpcs3ps5_import_99 __asm__("fmod") __attribute__((weak));
extern char rpcs3ps5_import_100 __asm__("fmodf") __attribute__((weak));
extern char rpcs3ps5_import_101 __asm__("fopen") __attribute__((weak));
extern char rpcs3ps5_import_102 __asm__("fprintf") __attribute__((weak));
extern char rpcs3ps5_import_103 __asm__("fputc") __attribute__((weak));
extern char rpcs3ps5_import_104 __asm__("fputs") __attribute__((weak));
extern char rpcs3ps5_import_105 __asm__("fputwc") __attribute__((weak));
extern char rpcs3ps5_import_106 __asm__("fread") __attribute__((weak));
extern char rpcs3ps5_import_107 __asm__("free") __attribute__((weak));
extern char rpcs3ps5_import_108 __asm__("freeifaddrs") __attribute__((weak));
extern char rpcs3ps5_import_109 __asm__("frexp") __attribute__((weak));
extern char rpcs3ps5_import_110 __asm__("frexpf") __attribute__((weak));
extern char rpcs3ps5_import_111 __asm__("frexpl") __attribute__((weak));
extern char rpcs3ps5_import_112 __asm__("fscanf") __attribute__((weak));
extern char rpcs3ps5_import_113 __asm__("fseek") __attribute__((weak));
extern char rpcs3ps5_import_114 __asm__("fseeko") __attribute__((weak));
extern char rpcs3ps5_import_115 __asm__("fstat") __attribute__((weak));
extern char rpcs3ps5_import_116 __asm__("fsync") __attribute__((weak));
extern char rpcs3ps5_import_117 __asm__("ftell") __attribute__((weak));
extern char rpcs3ps5_import_118 __asm__("ftello") __attribute__((weak));
extern char rpcs3ps5_import_119 __asm__("ftruncate") __attribute__((weak));
extern char rpcs3ps5_import_120 __asm__("futimes") __attribute__((weak));
extern char rpcs3ps5_import_121 __asm__("fwrite") __attribute__((weak));
extern char rpcs3ps5_import_122 __asm__("getc") __attribute__((weak));
extern char rpcs3ps5_import_123 __asm__("getdents") __attribute__((weak));
extern char rpcs3ps5_import_124 __asm__("getegid") __attribute__((weak));
extern char rpcs3ps5_import_125 __asm__("geteuid") __attribute__((weak));
extern char rpcs3ps5_import_126 __asm__("getgid") __attribute__((weak));
extern char rpcs3ps5_import_127 __asm__("getifaddrs") __attribute__((weak));
extern char rpcs3ps5_import_128 __asm__("getpagesize") __attribute__((weak));
extern char rpcs3ps5_import_129 __asm__("getpeername") __attribute__((weak));
extern char rpcs3ps5_import_130 __asm__("getpid") __attribute__((weak));
extern char rpcs3ps5_import_131 __asm__("getprogname") __attribute__((weak));
extern char rpcs3ps5_import_132 __asm__("getrlimit") __attribute__((weak));
extern char rpcs3ps5_import_133 __asm__("getrusage") __attribute__((weak));
extern char rpcs3ps5_import_134 __asm__("getsockname") __attribute__((weak));
extern char rpcs3ps5_import_135 __asm__("getsockopt") __attribute__((weak));
extern char rpcs3ps5_import_136 __asm__("gettimeofday") __attribute__((weak));
extern char rpcs3ps5_import_137 __asm__("getuid") __attribute__((weak));
extern char rpcs3ps5_import_138 __asm__("gmtime") __attribute__((weak));
extern char rpcs3ps5_import_139 __asm__("hypot") __attribute__((weak));
extern char rpcs3ps5_import_140 __asm__("hypotf") __attribute__((weak));
extern char rpcs3ps5_import_141 __asm__("in6addr_any") __attribute__((weak));
extern char rpcs3ps5_import_142 __asm__("ioctl") __attribute__((weak));
extern char rpcs3ps5_import_143 __asm__("isalnum") __attribute__((weak));
extern char rpcs3ps5_import_144 __asm__("isalpha") __attribute__((weak));
extern char rpcs3ps5_import_145 __asm__("isblank") __attribute__((weak));
extern char rpcs3ps5_import_146 __asm__("islower") __attribute__((weak));
extern char rpcs3ps5_import_147 __asm__("isprint") __attribute__((weak));
extern char rpcs3ps5_import_148 __asm__("isspace") __attribute__((weak));
extern char rpcs3ps5_import_149 __asm__("isupper") __attribute__((weak));
extern char rpcs3ps5_import_150 __asm__("iswalnum") __attribute__((weak));
extern char rpcs3ps5_import_151 __asm__("iswalpha") __attribute__((weak));
extern char rpcs3ps5_import_152 __asm__("iswblank") __attribute__((weak));
extern char rpcs3ps5_import_153 __asm__("iswcntrl") __attribute__((weak));
extern char rpcs3ps5_import_154 __asm__("iswctype") __attribute__((weak));
extern char rpcs3ps5_import_155 __asm__("iswdigit") __attribute__((weak));
extern char rpcs3ps5_import_156 __asm__("iswgraph") __attribute__((weak));
extern char rpcs3ps5_import_157 __asm__("iswlower") __attribute__((weak));
extern char rpcs3ps5_import_158 __asm__("iswprint") __attribute__((weak));
extern char rpcs3ps5_import_159 __asm__("iswpunct") __attribute__((weak));
extern char rpcs3ps5_import_160 __asm__("iswspace") __attribute__((weak));
extern char rpcs3ps5_import_161 __asm__("iswupper") __attribute__((weak));
extern char rpcs3ps5_import_162 __asm__("iswxdigit") __attribute__((weak));
extern char rpcs3ps5_import_163 __asm__("isxdigit") __attribute__((weak));
extern char rpcs3ps5_import_164 __asm__("kevent") __attribute__((weak));
extern char rpcs3ps5_import_165 __asm__("kill") __attribute__((weak));
extern char rpcs3ps5_import_166 __asm__("kqueue") __attribute__((weak));
extern char rpcs3ps5_import_167 __asm__("ldexp") __attribute__((weak));
extern char rpcs3ps5_import_168 __asm__("ldexpf") __attribute__((weak));
extern char rpcs3ps5_import_169 __asm__("listen") __attribute__((weak));
extern char rpcs3ps5_import_170 __asm__("llrint") __attribute__((weak));
extern char rpcs3ps5_import_171 __asm__("llround") __attribute__((weak));
extern char rpcs3ps5_import_172 __asm__("localtime") __attribute__((weak));
extern char rpcs3ps5_import_173 __asm__("log") __attribute__((weak));
extern char rpcs3ps5_import_174 __asm__("log10") __attribute__((weak));
extern char rpcs3ps5_import_175 __asm__("log10f") __attribute__((weak));
extern char rpcs3ps5_import_176 __asm__("log1p") __attribute__((weak));
extern char rpcs3ps5_import_177 __asm__("log1pf") __attribute__((weak));
extern char rpcs3ps5_import_178 __asm__("log2") __attribute__((weak));
extern char rpcs3ps5_import_179 __asm__("log2f") __attribute__((weak));
extern char rpcs3ps5_import_180 __asm__("logb") __attribute__((weak));
extern char rpcs3ps5_import_181 __asm__("logf") __attribute__((weak));
extern char rpcs3ps5_import_182 __asm__("longjmp") __attribute__((weak));
extern char rpcs3ps5_import_183 __asm__("lrint") __attribute__((weak));
extern char rpcs3ps5_import_184 __asm__("lrintf") __attribute__((weak));
extern char rpcs3ps5_import_185 __asm__("lround") __attribute__((weak));
extern char rpcs3ps5_import_186 __asm__("lroundf") __attribute__((weak));
extern char rpcs3ps5_import_187 __asm__("lseek") __attribute__((weak));
extern char rpcs3ps5_import_188 __asm__("lstat") __attribute__((weak));
extern char rpcs3ps5_import_189 __asm__("madvise") __attribute__((weak));
extern char rpcs3ps5_import_190 __asm__("malloc") __attribute__((weak));
extern char rpcs3ps5_import_191 __asm__("malloc_usable_size") __attribute__((weak));
extern char rpcs3ps5_import_192 __asm__("mbrlen") __attribute__((weak));
extern char rpcs3ps5_import_193 __asm__("mbrtowc") __attribute__((weak));
extern char rpcs3ps5_import_194 __asm__("mbsrtowcs") __attribute__((weak));
extern char rpcs3ps5_import_195 __asm__("mbtowc") __attribute__((weak));
extern char rpcs3ps5_import_196 __asm__("memchr") __attribute__((weak));
extern char rpcs3ps5_import_197 __asm__("memcmp") __attribute__((weak));
extern char rpcs3ps5_import_198 __asm__("memcpy") __attribute__((weak));
extern char rpcs3ps5_import_199 __asm__("memmove") __attribute__((weak));
extern char rpcs3ps5_import_200 __asm__("memrchr") __attribute__((weak));
extern char rpcs3ps5_import_201 __asm__("memset") __attribute__((weak));
extern char rpcs3ps5_import_202 __asm__("memset_s") __attribute__((weak));
extern char rpcs3ps5_import_203 __asm__("mkdir") __attribute__((weak));
extern char rpcs3ps5_import_204 __asm__("mktime") __attribute__((weak));
extern char rpcs3ps5_import_205 __asm__("mmap") __attribute__((weak));
extern char rpcs3ps5_import_206 __asm__("modf") __attribute__((weak));
extern char rpcs3ps5_import_207 __asm__("modff") __attribute__((weak));
extern char rpcs3ps5_import_208 __asm__("mprotect") __attribute__((weak));
extern char rpcs3ps5_import_209 __asm__("msync") __attribute__((weak));
extern char rpcs3ps5_import_210 __asm__("munmap") __attribute__((weak));
extern char rpcs3ps5_import_211 __asm__("nan") __attribute__((weak));
extern char rpcs3ps5_import_212 __asm__("nanf") __attribute__((weak));
extern char rpcs3ps5_import_213 __asm__("nanosleep") __attribute__((weak));
extern char rpcs3ps5_import_214 __asm__("nearbyint") __attribute__((weak));
extern char rpcs3ps5_import_215 __asm__("nearbyintf") __attribute__((weak));
extern char rpcs3ps5_import_216 __asm__("open") __attribute__((weak));
extern char rpcs3ps5_import_217 __asm__("perror") __attribute__((weak));
extern char rpcs3ps5_import_218 __asm__("pipe") __attribute__((weak));
extern char rpcs3ps5_import_219 __asm__("poll") __attribute__((weak));
extern char rpcs3ps5_import_220 __asm__("posix_memalign") __attribute__((weak));
extern char rpcs3ps5_import_221 __asm__("posix_spawn") __attribute__((weak));
extern char rpcs3ps5_import_222 __asm__("posix_spawn_file_actions_adddup2") __attribute__((weak));
extern char rpcs3ps5_import_223 __asm__("posix_spawn_file_actions_addopen") __attribute__((weak));
extern char rpcs3ps5_import_224 __asm__("posix_spawn_file_actions_destroy") __attribute__((weak));
extern char rpcs3ps5_import_225 __asm__("posix_spawn_file_actions_init") __attribute__((weak));
extern char rpcs3ps5_import_226 __asm__("pow") __attribute__((weak));
extern char rpcs3ps5_import_227 __asm__("powf") __attribute__((weak));
extern char rpcs3ps5_import_228 __asm__("pread") __attribute__((weak));
extern char rpcs3ps5_import_229 __asm__("printf") __attribute__((weak));
extern char rpcs3ps5_import_230 __asm__("pthread_atfork") __attribute__((weak));
extern char rpcs3ps5_import_231 __asm__("pthread_attr_destroy") __attribute__((weak));
extern char rpcs3ps5_import_232 __asm__("pthread_attr_get_np") __attribute__((weak));
extern char rpcs3ps5_import_233 __asm__("pthread_attr_getdetachstate") __attribute__((weak));
extern char rpcs3ps5_import_234 __asm__("pthread_attr_getinheritsched") __attribute__((weak));
extern char rpcs3ps5_import_235 __asm__("pthread_attr_getschedparam") __attribute__((weak));
extern char rpcs3ps5_import_236 __asm__("pthread_attr_getschedpolicy") __attribute__((weak));
extern char rpcs3ps5_import_237 __asm__("pthread_attr_getscope") __attribute__((weak));
extern char rpcs3ps5_import_238 __asm__("pthread_attr_getstack") __attribute__((weak));
extern char rpcs3ps5_import_239 __asm__("pthread_attr_getstackaddr") __attribute__((weak));
extern char rpcs3ps5_import_240 __asm__("pthread_attr_getstacksize") __attribute__((weak));
extern char rpcs3ps5_import_241 __asm__("pthread_attr_init") __attribute__((weak));
extern char rpcs3ps5_import_242 __asm__("pthread_attr_setdetachstate") __attribute__((weak));
extern char rpcs3ps5_import_243 __asm__("pthread_attr_setinheritsched") __attribute__((weak));
extern char rpcs3ps5_import_244 __asm__("pthread_attr_setschedparam") __attribute__((weak));
extern char rpcs3ps5_import_245 __asm__("pthread_attr_setschedpolicy") __attribute__((weak));
extern char rpcs3ps5_import_246 __asm__("pthread_attr_setscope") __attribute__((weak));
extern char rpcs3ps5_import_247 __asm__("pthread_attr_setstack") __attribute__((weak));
extern char rpcs3ps5_import_248 __asm__("pthread_attr_setstacksize") __attribute__((weak));
extern char rpcs3ps5_import_249 __asm__("pthread_barrier_destroy") __attribute__((weak));
extern char rpcs3ps5_import_250 __asm__("pthread_barrier_init") __attribute__((weak));
extern char rpcs3ps5_import_251 __asm__("pthread_barrier_wait") __attribute__((weak));
extern char rpcs3ps5_import_252 __asm__("pthread_cond_broadcast") __attribute__((weak));
extern char rpcs3ps5_import_253 __asm__("pthread_cond_destroy") __attribute__((weak));
extern char rpcs3ps5_import_254 __asm__("pthread_cond_init") __attribute__((weak));
extern char rpcs3ps5_import_255 __asm__("pthread_cond_signal") __attribute__((weak));
extern char rpcs3ps5_import_256 __asm__("pthread_cond_timedwait") __attribute__((weak));
extern char rpcs3ps5_import_257 __asm__("pthread_cond_wait") __attribute__((weak));
extern char rpcs3ps5_import_258 __asm__("pthread_condattr_destroy") __attribute__((weak));
extern char rpcs3ps5_import_259 __asm__("pthread_condattr_init") __attribute__((weak));
extern char rpcs3ps5_import_260 __asm__("pthread_condattr_setclock") __attribute__((weak));
extern char rpcs3ps5_import_261 __asm__("pthread_create") __attribute__((weak));
extern char rpcs3ps5_import_262 __asm__("pthread_detach") __attribute__((weak));
extern char rpcs3ps5_import_263 __asm__("pthread_equal") __attribute__((weak));
extern char rpcs3ps5_import_264 __asm__("pthread_exit") __attribute__((weak));
extern char rpcs3ps5_import_265 __asm__("pthread_getcpuclockid") __attribute__((weak));
extern char rpcs3ps5_import_266 __asm__("pthread_getschedparam") __attribute__((weak));
extern char rpcs3ps5_import_267 __asm__("pthread_getspecific") __attribute__((weak));
extern char rpcs3ps5_import_268 __asm__("pthread_getthreadid_np") __attribute__((weak));
extern char rpcs3ps5_import_269 __asm__("pthread_join") __attribute__((weak));
extern char rpcs3ps5_import_270 __asm__("pthread_key_create") __attribute__((weak));
extern char rpcs3ps5_import_271 __asm__("pthread_key_delete") __attribute__((weak));
extern char rpcs3ps5_import_272 __asm__("pthread_kill") __attribute__((weak));
extern char rpcs3ps5_import_273 __asm__("pthread_mutex_destroy") __attribute__((weak));
extern char rpcs3ps5_import_274 __asm__("pthread_mutex_init") __attribute__((weak));
extern char rpcs3ps5_import_275 __asm__("pthread_mutex_lock") __attribute__((weak));
extern char rpcs3ps5_import_276 __asm__("pthread_mutex_timedlock") __attribute__((weak));
extern char rpcs3ps5_import_277 __asm__("pthread_mutex_trylock") __attribute__((weak));
extern char rpcs3ps5_import_278 __asm__("pthread_mutex_unlock") __attribute__((weak));
extern char rpcs3ps5_import_279 __asm__("pthread_mutexattr_destroy") __attribute__((weak));
extern char rpcs3ps5_import_280 __asm__("pthread_mutexattr_init") __attribute__((weak));
extern char rpcs3ps5_import_281 __asm__("pthread_mutexattr_settype") __attribute__((weak));
extern char rpcs3ps5_import_282 __asm__("pthread_once") __attribute__((weak));
extern char rpcs3ps5_import_283 __asm__("pthread_rwlock_destroy") __attribute__((weak));
extern char rpcs3ps5_import_284 __asm__("pthread_rwlock_init") __attribute__((weak));
extern char rpcs3ps5_import_285 __asm__("pthread_rwlock_rdlock") __attribute__((weak));
extern char rpcs3ps5_import_286 __asm__("pthread_rwlock_unlock") __attribute__((weak));
extern char rpcs3ps5_import_287 __asm__("pthread_rwlock_wrlock") __attribute__((weak));
extern char rpcs3ps5_import_288 __asm__("pthread_self") __attribute__((weak));
extern char rpcs3ps5_import_289 __asm__("pthread_set_name_np") __attribute__((weak));
extern char rpcs3ps5_import_290 __asm__("pthread_setcancelstate") __attribute__((weak));
extern char rpcs3ps5_import_291 __asm__("pthread_setschedparam") __attribute__((weak));
extern char rpcs3ps5_import_292 __asm__("pthread_setspecific") __attribute__((weak));
extern char rpcs3ps5_import_293 __asm__("pthread_sigmask") __attribute__((weak));
extern char rpcs3ps5_import_294 __asm__("putchar") __attribute__((weak));
extern char rpcs3ps5_import_295 __asm__("puts") __attribute__((weak));
extern char rpcs3ps5_import_296 __asm__("pwrite") __attribute__((weak));
extern char rpcs3ps5_import_297 __asm__("qsort") __attribute__((weak));
extern char rpcs3ps5_import_298 __asm__("raise") __attribute__((weak));
extern char rpcs3ps5_import_299 __asm__("rand") __attribute__((weak));
extern char rpcs3ps5_import_300 __asm__("read") __attribute__((weak));
extern char rpcs3ps5_import_301 __asm__("realloc") __attribute__((weak));
extern char rpcs3ps5_import_302 __asm__("recv") __attribute__((weak));
extern char rpcs3ps5_import_303 __asm__("recvfrom") __attribute__((weak));
extern char rpcs3ps5_import_304 __asm__("remainder") __attribute__((weak));
extern char rpcs3ps5_import_305 __asm__("remainderf") __attribute__((weak));
extern char rpcs3ps5_import_306 __asm__("remove") __attribute__((weak));
extern char rpcs3ps5_import_307 __asm__("rename") __attribute__((weak));
extern char rpcs3ps5_import_308 __asm__("rewind") __attribute__((weak));
extern char rpcs3ps5_import_309 __asm__("rint") __attribute__((weak));
extern char rpcs3ps5_import_310 __asm__("rintf") __attribute__((weak));
extern char rpcs3ps5_import_311 __asm__("rmdir") __attribute__((weak));
extern char rpcs3ps5_import_312 __asm__("round") __attribute__((weak));
extern char rpcs3ps5_import_313 __asm__("roundf") __attribute__((weak));
extern char rpcs3ps5_import_314 __asm__("scalbn") __attribute__((weak));
extern char rpcs3ps5_import_315 __asm__("sceAudioOutClose") __attribute__((weak));
extern char rpcs3ps5_import_316 __asm__("sceAudioOutInit") __attribute__((weak));
extern char rpcs3ps5_import_317 __asm__("sceAudioOutOpen") __attribute__((weak));
extern char rpcs3ps5_import_318 __asm__("sceAudioOutOutput") __attribute__((weak));
extern char rpcs3ps5_import_319 __asm__("sceKernelAllocateDirectMemory") __attribute__((weak));
extern char rpcs3ps5_import_320 __asm__("sceKernelAvailableDirectMemorySize") __attribute__((weak));
extern char rpcs3ps5_import_321 __asm__("sceKernelAvailableFlexibleMemorySize") __attribute__((weak));
extern char rpcs3ps5_import_322 __asm__("sceKernelClockGettime") __attribute__((weak));
extern char rpcs3ps5_import_323 __asm__("sceKernelConfiguredFlexibleMemorySize") __attribute__((weak));
extern char rpcs3ps5_import_324 __asm__("sceKernelDebugOutText") __attribute__((weak));
extern char rpcs3ps5_import_325 __asm__("sceKernelGetCurrentCpu") __attribute__((weak));
extern char rpcs3ps5_import_326 __asm__("sceKernelGetDirectMemorySize") __attribute__((weak));
extern char rpcs3ps5_import_327 __asm__("sceKernelGetSystemSwVersion") __attribute__((weak));
extern char rpcs3ps5_import_328 __asm__("sceKernelGetTscFrequency") __attribute__((weak));
extern char rpcs3ps5_import_329 __asm__("sceKernelJitCreateAliasOfSharedMemory") __attribute__((weak));
extern char rpcs3ps5_import_330 __asm__("sceKernelJitCreateSharedMemory") __attribute__((weak));
extern char rpcs3ps5_import_331 __asm__("sceKernelJitMapSharedMemory") __attribute__((weak));
extern char rpcs3ps5_import_332 __asm__("sceKernelMapDirectMemory") __attribute__((weak));
extern char rpcs3ps5_import_333 __asm__("sceKernelMprotect") __attribute__((weak));
extern char rpcs3ps5_import_334 __asm__("sceKernelMunmap") __attribute__((weak));
extern char rpcs3ps5_import_335 __asm__("sceKernelReadTsc") __attribute__((weak));
extern char rpcs3ps5_import_336 __asm__("sceKernelReleaseDirectMemory") __attribute__((weak));
extern char rpcs3ps5_import_337 __asm__("sceKernelReserveVirtualRange") __attribute__((weak));
extern char rpcs3ps5_import_338 __asm__("sceKernelUsleep") __attribute__((weak));
extern char rpcs3ps5_import_339 __asm__("scePadInit") __attribute__((weak));
extern char rpcs3ps5_import_340 __asm__("scePadOpen") __attribute__((weak));
extern char rpcs3ps5_import_341 __asm__("scePadRead") __attribute__((weak));
extern char rpcs3ps5_import_342 __asm__("scePadSetLightBar") __attribute__((weak));
extern char rpcs3ps5_import_343 __asm__("scePadSetVibration") __attribute__((weak));
extern char rpcs3ps5_import_344 __asm__("scePadSetVibrationMode") __attribute__((weak));
extern char rpcs3ps5_import_345 __asm__("scePthreadGetaffinity") __attribute__((weak));
extern char rpcs3ps5_import_346 __asm__("scePthreadSetaffinity") __attribute__((weak));
extern char rpcs3ps5_import_347 __asm__("scePthreadYield") __attribute__((weak));
extern char rpcs3ps5_import_348 __asm__("sceSystemServiceHideSplashScreen") __attribute__((weak));
extern char rpcs3ps5_import_349 __asm__("sceSystemServiceLoadExec") __attribute__((weak));
extern char rpcs3ps5_import_350 __asm__("sceUserServiceGetInitialUser") __attribute__((weak));
extern char rpcs3ps5_import_351 __asm__("sceUserServiceInitialize") __attribute__((weak));
extern char rpcs3ps5_import_352 __asm__("sceVideoOutConfigureOutput") __attribute__((weak));
extern char rpcs3ps5_import_353 __asm__("sceVideoOutGetFlipStatus") __attribute__((weak));
extern char rpcs3ps5_import_354 __asm__("sceVideoOutIsOutputSupported") __attribute__((weak));
extern char rpcs3ps5_import_355 __asm__("sceVideoOutOpen") __attribute__((weak));
extern char rpcs3ps5_import_356 __asm__("sceVideoOutRegisterBuffers2") __attribute__((weak));
extern char rpcs3ps5_import_357 __asm__("sceVideoOutSetBufferAttribute2") __attribute__((weak));
extern char rpcs3ps5_import_358 __asm__("sceVideoOutSetFlipRate") __attribute__((weak));
extern char rpcs3ps5_import_359 __asm__("sceVideoOutSubmitFlip") __attribute__((weak));
extern char rpcs3ps5_import_360 __asm__("sceVideoOutWaitVblank") __attribute__((weak));
extern char rpcs3ps5_import_361 __asm__("sched_get_priority_max") __attribute__((weak));
extern char rpcs3ps5_import_362 __asm__("sched_get_priority_min") __attribute__((weak));
extern char rpcs3ps5_import_363 __asm__("select") __attribute__((weak));
extern char rpcs3ps5_import_364 __asm__("sem_destroy") __attribute__((weak));
extern char rpcs3ps5_import_365 __asm__("sem_init") __attribute__((weak));
extern char rpcs3ps5_import_366 __asm__("sem_post") __attribute__((weak));
extern char rpcs3ps5_import_367 __asm__("sem_wait") __attribute__((weak));
extern char rpcs3ps5_import_368 __asm__("send") __attribute__((weak));
extern char rpcs3ps5_import_369 __asm__("sendto") __attribute__((weak));
extern char rpcs3ps5_import_370 __asm__("setjmp") __attribute__((weak));
extern char rpcs3ps5_import_371 __asm__("setlocale") __attribute__((weak));
extern char rpcs3ps5_import_372 __asm__("setrlimit") __attribute__((weak));
extern char rpcs3ps5_import_373 __asm__("setsockopt") __attribute__((weak));
extern char rpcs3ps5_import_374 __asm__("setvbuf") __attribute__((weak));
extern char rpcs3ps5_import_375 __asm__("shm_open") __attribute__((weak));
extern char rpcs3ps5_import_376 __asm__("shm_unlink") __attribute__((weak));
extern char rpcs3ps5_import_377 __asm__("shutdown") __attribute__((weak));
extern char rpcs3ps5_import_378 __asm__("sigaction") __attribute__((weak));
extern char rpcs3ps5_import_379 __asm__("sigaddset") __attribute__((weak));
extern char rpcs3ps5_import_380 __asm__("sigaltstack") __attribute__((weak));
extern char rpcs3ps5_import_381 __asm__("sigdelset") __attribute__((weak));
extern char rpcs3ps5_import_382 __asm__("sigemptyset") __attribute__((weak));
extern char rpcs3ps5_import_383 __asm__("sigfillset") __attribute__((weak));
extern char rpcs3ps5_import_384 __asm__("siglongjmp") __attribute__((weak));
extern char rpcs3ps5_import_385 __asm__("sigprocmask") __attribute__((weak));
extern char rpcs3ps5_import_386 __asm__("sigsetjmp") __attribute__((weak));
extern char rpcs3ps5_import_387 __asm__("sin") __attribute__((weak));
extern char rpcs3ps5_import_388 __asm__("sincos") __attribute__((weak));
extern char rpcs3ps5_import_389 __asm__("sincosf") __attribute__((weak));
extern char rpcs3ps5_import_390 __asm__("sinf") __attribute__((weak));
extern char rpcs3ps5_import_391 __asm__("sinh") __attribute__((weak));
extern char rpcs3ps5_import_392 __asm__("sinhf") __attribute__((weak));
extern char rpcs3ps5_import_393 __asm__("snprintf") __attribute__((weak));
extern char rpcs3ps5_import_394 __asm__("socket") __attribute__((weak));
extern char rpcs3ps5_import_395 __asm__("sprintf") __attribute__((weak));
extern char rpcs3ps5_import_396 __asm__("sqrt") __attribute__((weak));
extern char rpcs3ps5_import_397 __asm__("sqrtf") __attribute__((weak));
extern char rpcs3ps5_import_398 __asm__("srand") __attribute__((weak));
extern char rpcs3ps5_import_399 __asm__("sscanf") __attribute__((weak));
extern char rpcs3ps5_import_400 __asm__("stat") __attribute__((weak));
extern char rpcs3ps5_import_401 __asm__("strcasecmp") __attribute__((weak));
extern char rpcs3ps5_import_402 __asm__("strcat") __attribute__((weak));
extern char rpcs3ps5_import_403 __asm__("strchr") __attribute__((weak));
extern char rpcs3ps5_import_404 __asm__("strcmp") __attribute__((weak));
extern char rpcs3ps5_import_405 __asm__("strcoll") __attribute__((weak));
extern char rpcs3ps5_import_406 __asm__("strcpy") __attribute__((weak));
extern char rpcs3ps5_import_407 __asm__("strcspn") __attribute__((weak));
extern char rpcs3ps5_import_408 __asm__("strdup") __attribute__((weak));
extern char rpcs3ps5_import_409 __asm__("strerror") __attribute__((weak));
extern char rpcs3ps5_import_410 __asm__("strerror_r") __attribute__((weak));
extern char rpcs3ps5_import_411 __asm__("strftime") __attribute__((weak));
extern char rpcs3ps5_import_412 __asm__("strlen") __attribute__((weak));
extern char rpcs3ps5_import_413 __asm__("strncasecmp") __attribute__((weak));
extern char rpcs3ps5_import_414 __asm__("strncat") __attribute__((weak));
extern char rpcs3ps5_import_415 __asm__("strncmp") __attribute__((weak));
extern char rpcs3ps5_import_416 __asm__("strncpy") __attribute__((weak));
extern char rpcs3ps5_import_417 __asm__("strndup") __attribute__((weak));
extern char rpcs3ps5_import_418 __asm__("strnlen") __attribute__((weak));
extern char rpcs3ps5_import_419 __asm__("strpbrk") __attribute__((weak));
extern char rpcs3ps5_import_420 __asm__("strrchr") __attribute__((weak));
extern char rpcs3ps5_import_421 __asm__("strspn") __attribute__((weak));
extern char rpcs3ps5_import_422 __asm__("strstr") __attribute__((weak));
extern char rpcs3ps5_import_423 __asm__("strtod") __attribute__((weak));
extern char rpcs3ps5_import_424 __asm__("strtof") __attribute__((weak));
extern char rpcs3ps5_import_425 __asm__("strtok") __attribute__((weak));
extern char rpcs3ps5_import_426 __asm__("strtok_r") __attribute__((weak));
extern char rpcs3ps5_import_427 __asm__("strtol") __attribute__((weak));
extern char rpcs3ps5_import_428 __asm__("strtold") __attribute__((weak));
extern char rpcs3ps5_import_429 __asm__("strtoll") __attribute__((weak));
extern char rpcs3ps5_import_430 __asm__("strtoul") __attribute__((weak));
extern char rpcs3ps5_import_431 __asm__("strtoull") __attribute__((weak));
extern char rpcs3ps5_import_432 __asm__("strxfrm") __attribute__((weak));
extern char rpcs3ps5_import_433 __asm__("swprintf") __attribute__((weak));
extern char rpcs3ps5_import_434 __asm__("sync") __attribute__((weak));
extern char rpcs3ps5_import_435 __asm__("sysconf") __attribute__((weak));
extern char rpcs3ps5_import_436 __asm__("sysctl") __attribute__((weak));
extern char rpcs3ps5_import_437 __asm__("sysctlbyname") __attribute__((weak));
extern char rpcs3ps5_import_438 __asm__("syslog") __attribute__((weak));
extern char rpcs3ps5_import_439 __asm__("system") __attribute__((weak));
extern char rpcs3ps5_import_440 __asm__("tan") __attribute__((weak));
extern char rpcs3ps5_import_441 __asm__("tanf") __attribute__((weak));
extern char rpcs3ps5_import_442 __asm__("tanh") __attribute__((weak));
extern char rpcs3ps5_import_443 __asm__("tanhf") __attribute__((weak));
extern char rpcs3ps5_import_444 __asm__("time") __attribute__((weak));
extern char rpcs3ps5_import_445 __asm__("tolower") __attribute__((weak));
extern char rpcs3ps5_import_446 __asm__("toupper") __attribute__((weak));
extern char rpcs3ps5_import_447 __asm__("towlower") __attribute__((weak));
extern char rpcs3ps5_import_448 __asm__("towupper") __attribute__((weak));
extern char rpcs3ps5_import_449 __asm__("trunc") __attribute__((weak));
extern char rpcs3ps5_import_450 __asm__("truncate") __attribute__((weak));
extern char rpcs3ps5_import_451 __asm__("truncf") __attribute__((weak));
extern char rpcs3ps5_import_452 __asm__("tzset") __attribute__((weak));
extern char rpcs3ps5_import_453 __asm__("ungetc") __attribute__((weak));
extern char rpcs3ps5_import_454 __asm__("ungetwc") __attribute__((weak));
extern char rpcs3ps5_import_455 __asm__("unlink") __attribute__((weak));
extern char rpcs3ps5_import_456 __asm__("usleep") __attribute__((weak));
extern char rpcs3ps5_import_457 __asm__("utime") __attribute__((weak));
extern char rpcs3ps5_import_458 __asm__("utimes") __attribute__((weak));
extern char rpcs3ps5_import_459 __asm__("vasprintf") __attribute__((weak));
extern char rpcs3ps5_import_460 __asm__("vfprintf") __attribute__((weak));
extern char rpcs3ps5_import_461 __asm__("vsnprintf") __attribute__((weak));
extern char rpcs3ps5_import_462 __asm__("vsprintf") __attribute__((weak));
extern char rpcs3ps5_import_463 __asm__("vsscanf") __attribute__((weak));
extern char rpcs3ps5_import_464 __asm__("wait") __attribute__((weak));
extern char rpcs3ps5_import_465 __asm__("wcrtomb") __attribute__((weak));
extern char rpcs3ps5_import_466 __asm__("wcscoll") __attribute__((weak));
extern char rpcs3ps5_import_467 __asm__("wcslen") __attribute__((weak));
extern char rpcs3ps5_import_468 __asm__("wcstod") __attribute__((weak));
extern char rpcs3ps5_import_469 __asm__("wcstof") __attribute__((weak));
extern char rpcs3ps5_import_470 __asm__("wcstol") __attribute__((weak));
extern char rpcs3ps5_import_471 __asm__("wcstold") __attribute__((weak));
extern char rpcs3ps5_import_472 __asm__("wcstoll") __attribute__((weak));
extern char rpcs3ps5_import_473 __asm__("wcstoul") __attribute__((weak));
extern char rpcs3ps5_import_474 __asm__("wcstoull") __attribute__((weak));
extern char rpcs3ps5_import_475 __asm__("wcsxfrm") __attribute__((weak));
extern char rpcs3ps5_import_476 __asm__("wctob") __attribute__((weak));
extern char rpcs3ps5_import_477 __asm__("wctype") __attribute__((weak));
extern char rpcs3ps5_import_478 __asm__("wmemchr") __attribute__((weak));
extern char rpcs3ps5_import_479 __asm__("wmemcmp") __attribute__((weak));
extern char rpcs3ps5_import_480 __asm__("write") __attribute__((weak));
extern char rpcs3ps5_import_481 __asm__("writev") __attribute__((weak));

static const struct { const char *name; const void *address; } g_imports[] = {
    {"_CurrentRuneLocale", &rpcs3ps5_import_0},
    {"_DefaultRuneLocale", &rpcs3ps5_import_1},
    {"_Exit", &rpcs3ps5_import_2},
    {"_Unwind_Backtrace", &rpcs3ps5_import_3},
    {"__cxa_atexit", &rpcs3ps5_import_4},
    {"__error", &rpcs3ps5_import_5},
    {"__fpclassifyd", &rpcs3ps5_import_6},
    {"__inet_ntop", &rpcs3ps5_import_7},
    {"__inet_pton", &rpcs3ps5_import_8},
    {"__isfinite", &rpcs3ps5_import_9},
    {"__isfinitef", &rpcs3ps5_import_10},
    {"__isinf", &rpcs3ps5_import_11},
    {"__isinff", &rpcs3ps5_import_12},
    {"__isnormal", &rpcs3ps5_import_13},
    {"__isnormalf", &rpcs3ps5_import_14},
    {"__isthreaded", &rpcs3ps5_import_15},
    {"__mb_cur_max", &rpcs3ps5_import_16},
    {"__mb_sb_limit", &rpcs3ps5_import_17},
    {"__stack_chk_fail", &rpcs3ps5_import_18},
    {"__stack_chk_guard", &rpcs3ps5_import_19},
    {"__stderrp", &rpcs3ps5_import_20},
    {"__stdinp", &rpcs3ps5_import_21},
    {"__stdoutp", &rpcs3ps5_import_22},
    {"_exit", &rpcs3ps5_import_23},
    {"_init_env", &rpcs3ps5_import_24},
    {"_umtx_op", &rpcs3ps5_import_25},
    {"abort", &rpcs3ps5_import_26},
    {"accept", &rpcs3ps5_import_27},
    {"acos", &rpcs3ps5_import_28},
    {"acosf", &rpcs3ps5_import_29},
    {"alarm", &rpcs3ps5_import_30},
    {"asin", &rpcs3ps5_import_31},
    {"asinf", &rpcs3ps5_import_32},
    {"asprintf", &rpcs3ps5_import_33},
    {"atan", &rpcs3ps5_import_34},
    {"atan2", &rpcs3ps5_import_35},
    {"atan2f", &rpcs3ps5_import_36},
    {"atanf", &rpcs3ps5_import_37},
    {"atexit", &rpcs3ps5_import_38},
    {"atof", &rpcs3ps5_import_39},
    {"atoi", &rpcs3ps5_import_40},
    {"basename", &rpcs3ps5_import_41},
    {"bind", &rpcs3ps5_import_42},
    {"bsearch", &rpcs3ps5_import_43},
    {"btowc", &rpcs3ps5_import_44},
    {"calloc", &rpcs3ps5_import_45},
    {"cbrt", &rpcs3ps5_import_46},
    {"cbrtf", &rpcs3ps5_import_47},
    {"ceil", &rpcs3ps5_import_48},
    {"ceilf", &rpcs3ps5_import_49},
    {"chdir", &rpcs3ps5_import_50},
    {"chmod", &rpcs3ps5_import_51},
    {"clock", &rpcs3ps5_import_52},
    {"close", &rpcs3ps5_import_53},
    {"connect", &rpcs3ps5_import_54},
    {"copysign", &rpcs3ps5_import_55},
    {"copysignf", &rpcs3ps5_import_56},
    {"cos", &rpcs3ps5_import_57},
    {"cosf", &rpcs3ps5_import_58},
    {"cosh", &rpcs3ps5_import_59},
    {"coshf", &rpcs3ps5_import_60},
    {"ctime", &rpcs3ps5_import_61},
    {"dirname", &rpcs3ps5_import_62},
    {"dup", &rpcs3ps5_import_63},
    {"dup2", &rpcs3ps5_import_64},
    {"environ", &rpcs3ps5_import_65},
    {"erf", &rpcs3ps5_import_66},
    {"execv", &rpcs3ps5_import_67},
    {"execve", &rpcs3ps5_import_68},
    {"exit", &rpcs3ps5_import_69},
    {"exp", &rpcs3ps5_import_70},
    {"exp2", &rpcs3ps5_import_71},
    {"exp2f", &rpcs3ps5_import_72},
    {"exp2l", &rpcs3ps5_import_73},
    {"expf", &rpcs3ps5_import_74},
    {"expm1", &rpcs3ps5_import_75},
    {"expm1f", &rpcs3ps5_import_76},
    {"fabs", &rpcs3ps5_import_77},
    {"fabsf", &rpcs3ps5_import_78},
    {"fchmod", &rpcs3ps5_import_79},
    {"fclose", &rpcs3ps5_import_80},
    {"fcntl", &rpcs3ps5_import_81},
    {"fdopen", &rpcs3ps5_import_82},
    {"feof", &rpcs3ps5_import_83},
    {"ferror", &rpcs3ps5_import_84},
    {"fflush", &rpcs3ps5_import_85},
    {"fgetc", &rpcs3ps5_import_86},
    {"fgets", &rpcs3ps5_import_87},
    {"fgetwc", &rpcs3ps5_import_88},
    {"fileno", &rpcs3ps5_import_89},
    {"flock", &rpcs3ps5_import_90},
    {"floor", &rpcs3ps5_import_91},
    {"floorf", &rpcs3ps5_import_92},
    {"fma", &rpcs3ps5_import_93},
    {"fmaf", &rpcs3ps5_import_94},
    {"fmax", &rpcs3ps5_import_95},
    {"fmaxf", &rpcs3ps5_import_96},
    {"fmin", &rpcs3ps5_import_97},
    {"fminf", &rpcs3ps5_import_98},
    {"fmod", &rpcs3ps5_import_99},
    {"fmodf", &rpcs3ps5_import_100},
    {"fopen", &rpcs3ps5_import_101},
    {"fprintf", &rpcs3ps5_import_102},
    {"fputc", &rpcs3ps5_import_103},
    {"fputs", &rpcs3ps5_import_104},
    {"fputwc", &rpcs3ps5_import_105},
    {"fread", &rpcs3ps5_import_106},
    {"free", &rpcs3ps5_import_107},
    {"freeifaddrs", &rpcs3ps5_import_108},
    {"frexp", &rpcs3ps5_import_109},
    {"frexpf", &rpcs3ps5_import_110},
    {"frexpl", &rpcs3ps5_import_111},
    {"fscanf", &rpcs3ps5_import_112},
    {"fseek", &rpcs3ps5_import_113},
    {"fseeko", &rpcs3ps5_import_114},
    {"fstat", &rpcs3ps5_import_115},
    {"fsync", &rpcs3ps5_import_116},
    {"ftell", &rpcs3ps5_import_117},
    {"ftello", &rpcs3ps5_import_118},
    {"ftruncate", &rpcs3ps5_import_119},
    {"futimes", &rpcs3ps5_import_120},
    {"fwrite", &rpcs3ps5_import_121},
    {"getc", &rpcs3ps5_import_122},
    {"getdents", &rpcs3ps5_import_123},
    {"getegid", &rpcs3ps5_import_124},
    {"geteuid", &rpcs3ps5_import_125},
    {"getgid", &rpcs3ps5_import_126},
    {"getifaddrs", &rpcs3ps5_import_127},
    {"getpagesize", &rpcs3ps5_import_128},
    {"getpeername", &rpcs3ps5_import_129},
    {"getpid", &rpcs3ps5_import_130},
    {"getprogname", &rpcs3ps5_import_131},
    {"getrlimit", &rpcs3ps5_import_132},
    {"getrusage", &rpcs3ps5_import_133},
    {"getsockname", &rpcs3ps5_import_134},
    {"getsockopt", &rpcs3ps5_import_135},
    {"gettimeofday", &rpcs3ps5_import_136},
    {"getuid", &rpcs3ps5_import_137},
    {"gmtime", &rpcs3ps5_import_138},
    {"hypot", &rpcs3ps5_import_139},
    {"hypotf", &rpcs3ps5_import_140},
    {"in6addr_any", &rpcs3ps5_import_141},
    {"ioctl", &rpcs3ps5_import_142},
    {"isalnum", &rpcs3ps5_import_143},
    {"isalpha", &rpcs3ps5_import_144},
    {"isblank", &rpcs3ps5_import_145},
    {"islower", &rpcs3ps5_import_146},
    {"isprint", &rpcs3ps5_import_147},
    {"isspace", &rpcs3ps5_import_148},
    {"isupper", &rpcs3ps5_import_149},
    {"iswalnum", &rpcs3ps5_import_150},
    {"iswalpha", &rpcs3ps5_import_151},
    {"iswblank", &rpcs3ps5_import_152},
    {"iswcntrl", &rpcs3ps5_import_153},
    {"iswctype", &rpcs3ps5_import_154},
    {"iswdigit", &rpcs3ps5_import_155},
    {"iswgraph", &rpcs3ps5_import_156},
    {"iswlower", &rpcs3ps5_import_157},
    {"iswprint", &rpcs3ps5_import_158},
    {"iswpunct", &rpcs3ps5_import_159},
    {"iswspace", &rpcs3ps5_import_160},
    {"iswupper", &rpcs3ps5_import_161},
    {"iswxdigit", &rpcs3ps5_import_162},
    {"isxdigit", &rpcs3ps5_import_163},
    {"kevent", &rpcs3ps5_import_164},
    {"kill", &rpcs3ps5_import_165},
    {"kqueue", &rpcs3ps5_import_166},
    {"ldexp", &rpcs3ps5_import_167},
    {"ldexpf", &rpcs3ps5_import_168},
    {"listen", &rpcs3ps5_import_169},
    {"llrint", &rpcs3ps5_import_170},
    {"llround", &rpcs3ps5_import_171},
    {"localtime", &rpcs3ps5_import_172},
    {"log", &rpcs3ps5_import_173},
    {"log10", &rpcs3ps5_import_174},
    {"log10f", &rpcs3ps5_import_175},
    {"log1p", &rpcs3ps5_import_176},
    {"log1pf", &rpcs3ps5_import_177},
    {"log2", &rpcs3ps5_import_178},
    {"log2f", &rpcs3ps5_import_179},
    {"logb", &rpcs3ps5_import_180},
    {"logf", &rpcs3ps5_import_181},
    {"longjmp", &rpcs3ps5_import_182},
    {"lrint", &rpcs3ps5_import_183},
    {"lrintf", &rpcs3ps5_import_184},
    {"lround", &rpcs3ps5_import_185},
    {"lroundf", &rpcs3ps5_import_186},
    {"lseek", &rpcs3ps5_import_187},
    {"lstat", &rpcs3ps5_import_188},
    {"madvise", &rpcs3ps5_import_189},
    {"malloc", &rpcs3ps5_import_190},
    {"malloc_usable_size", &rpcs3ps5_import_191},
    {"mbrlen", &rpcs3ps5_import_192},
    {"mbrtowc", &rpcs3ps5_import_193},
    {"mbsrtowcs", &rpcs3ps5_import_194},
    {"mbtowc", &rpcs3ps5_import_195},
    {"memchr", &rpcs3ps5_import_196},
    {"memcmp", &rpcs3ps5_import_197},
    {"memcpy", &rpcs3ps5_import_198},
    {"memmove", &rpcs3ps5_import_199},
    {"memrchr", &rpcs3ps5_import_200},
    {"memset", &rpcs3ps5_import_201},
    {"memset_s", &rpcs3ps5_import_202},
    {"mkdir", &rpcs3ps5_import_203},
    {"mktime", &rpcs3ps5_import_204},
    {"mmap", &rpcs3ps5_import_205},
    {"modf", &rpcs3ps5_import_206},
    {"modff", &rpcs3ps5_import_207},
    {"mprotect", &rpcs3ps5_import_208},
    {"msync", &rpcs3ps5_import_209},
    {"munmap", &rpcs3ps5_import_210},
    {"nan", &rpcs3ps5_import_211},
    {"nanf", &rpcs3ps5_import_212},
    {"nanosleep", &rpcs3ps5_import_213},
    {"nearbyint", &rpcs3ps5_import_214},
    {"nearbyintf", &rpcs3ps5_import_215},
    {"open", &rpcs3ps5_import_216},
    {"perror", &rpcs3ps5_import_217},
    {"pipe", &rpcs3ps5_import_218},
    {"poll", &rpcs3ps5_import_219},
    {"posix_memalign", &rpcs3ps5_import_220},
    {"posix_spawn", &rpcs3ps5_import_221},
    {"posix_spawn_file_actions_adddup2", &rpcs3ps5_import_222},
    {"posix_spawn_file_actions_addopen", &rpcs3ps5_import_223},
    {"posix_spawn_file_actions_destroy", &rpcs3ps5_import_224},
    {"posix_spawn_file_actions_init", &rpcs3ps5_import_225},
    {"pow", &rpcs3ps5_import_226},
    {"powf", &rpcs3ps5_import_227},
    {"pread", &rpcs3ps5_import_228},
    {"printf", &rpcs3ps5_import_229},
    {"pthread_atfork", &rpcs3ps5_import_230},
    {"pthread_attr_destroy", &rpcs3ps5_import_231},
    {"pthread_attr_get_np", &rpcs3ps5_import_232},
    {"pthread_attr_getdetachstate", &rpcs3ps5_import_233},
    {"pthread_attr_getinheritsched", &rpcs3ps5_import_234},
    {"pthread_attr_getschedparam", &rpcs3ps5_import_235},
    {"pthread_attr_getschedpolicy", &rpcs3ps5_import_236},
    {"pthread_attr_getscope", &rpcs3ps5_import_237},
    {"pthread_attr_getstack", &rpcs3ps5_import_238},
    {"pthread_attr_getstackaddr", &rpcs3ps5_import_239},
    {"pthread_attr_getstacksize", &rpcs3ps5_import_240},
    {"pthread_attr_init", &rpcs3ps5_import_241},
    {"pthread_attr_setdetachstate", &rpcs3ps5_import_242},
    {"pthread_attr_setinheritsched", &rpcs3ps5_import_243},
    {"pthread_attr_setschedparam", &rpcs3ps5_import_244},
    {"pthread_attr_setschedpolicy", &rpcs3ps5_import_245},
    {"pthread_attr_setscope", &rpcs3ps5_import_246},
    {"pthread_attr_setstack", &rpcs3ps5_import_247},
    {"pthread_attr_setstacksize", &rpcs3ps5_import_248},
    {"pthread_barrier_destroy", &rpcs3ps5_import_249},
    {"pthread_barrier_init", &rpcs3ps5_import_250},
    {"pthread_barrier_wait", &rpcs3ps5_import_251},
    {"pthread_cond_broadcast", &rpcs3ps5_import_252},
    {"pthread_cond_destroy", &rpcs3ps5_import_253},
    {"pthread_cond_init", &rpcs3ps5_import_254},
    {"pthread_cond_signal", &rpcs3ps5_import_255},
    {"pthread_cond_timedwait", &rpcs3ps5_import_256},
    {"pthread_cond_wait", &rpcs3ps5_import_257},
    {"pthread_condattr_destroy", &rpcs3ps5_import_258},
    {"pthread_condattr_init", &rpcs3ps5_import_259},
    {"pthread_condattr_setclock", &rpcs3ps5_import_260},
    {"pthread_create", &rpcs3ps5_import_261},
    {"pthread_detach", &rpcs3ps5_import_262},
    {"pthread_equal", &rpcs3ps5_import_263},
    {"pthread_exit", &rpcs3ps5_import_264},
    {"pthread_getcpuclockid", &rpcs3ps5_import_265},
    {"pthread_getschedparam", &rpcs3ps5_import_266},
    {"pthread_getspecific", &rpcs3ps5_import_267},
    {"pthread_getthreadid_np", &rpcs3ps5_import_268},
    {"pthread_join", &rpcs3ps5_import_269},
    {"pthread_key_create", &rpcs3ps5_import_270},
    {"pthread_key_delete", &rpcs3ps5_import_271},
    {"pthread_kill", &rpcs3ps5_import_272},
    {"pthread_mutex_destroy", &rpcs3ps5_import_273},
    {"pthread_mutex_init", &rpcs3ps5_import_274},
    {"pthread_mutex_lock", &rpcs3ps5_import_275},
    {"pthread_mutex_timedlock", &rpcs3ps5_import_276},
    {"pthread_mutex_trylock", &rpcs3ps5_import_277},
    {"pthread_mutex_unlock", &rpcs3ps5_import_278},
    {"pthread_mutexattr_destroy", &rpcs3ps5_import_279},
    {"pthread_mutexattr_init", &rpcs3ps5_import_280},
    {"pthread_mutexattr_settype", &rpcs3ps5_import_281},
    {"pthread_once", &rpcs3ps5_import_282},
    {"pthread_rwlock_destroy", &rpcs3ps5_import_283},
    {"pthread_rwlock_init", &rpcs3ps5_import_284},
    {"pthread_rwlock_rdlock", &rpcs3ps5_import_285},
    {"pthread_rwlock_unlock", &rpcs3ps5_import_286},
    {"pthread_rwlock_wrlock", &rpcs3ps5_import_287},
    {"pthread_self", &rpcs3ps5_import_288},
    {"pthread_set_name_np", &rpcs3ps5_import_289},
    {"pthread_setcancelstate", &rpcs3ps5_import_290},
    {"pthread_setschedparam", &rpcs3ps5_import_291},
    {"pthread_setspecific", &rpcs3ps5_import_292},
    {"pthread_sigmask", &rpcs3ps5_import_293},
    {"putchar", &rpcs3ps5_import_294},
    {"puts", &rpcs3ps5_import_295},
    {"pwrite", &rpcs3ps5_import_296},
    {"qsort", &rpcs3ps5_import_297},
    {"raise", &rpcs3ps5_import_298},
    {"rand", &rpcs3ps5_import_299},
    {"read", &rpcs3ps5_import_300},
    {"realloc", &rpcs3ps5_import_301},
    {"recv", &rpcs3ps5_import_302},
    {"recvfrom", &rpcs3ps5_import_303},
    {"remainder", &rpcs3ps5_import_304},
    {"remainderf", &rpcs3ps5_import_305},
    {"remove", &rpcs3ps5_import_306},
    {"rename", &rpcs3ps5_import_307},
    {"rewind", &rpcs3ps5_import_308},
    {"rint", &rpcs3ps5_import_309},
    {"rintf", &rpcs3ps5_import_310},
    {"rmdir", &rpcs3ps5_import_311},
    {"round", &rpcs3ps5_import_312},
    {"roundf", &rpcs3ps5_import_313},
    {"scalbn", &rpcs3ps5_import_314},
    {"sceAudioOutClose", &rpcs3ps5_import_315},
    {"sceAudioOutInit", &rpcs3ps5_import_316},
    {"sceAudioOutOpen", &rpcs3ps5_import_317},
    {"sceAudioOutOutput", &rpcs3ps5_import_318},
    {"sceKernelAllocateDirectMemory", &rpcs3ps5_import_319},
    {"sceKernelAvailableDirectMemorySize", &rpcs3ps5_import_320},
    {"sceKernelAvailableFlexibleMemorySize", &rpcs3ps5_import_321},
    {"sceKernelClockGettime", &rpcs3ps5_import_322},
    {"sceKernelConfiguredFlexibleMemorySize", &rpcs3ps5_import_323},
    {"sceKernelDebugOutText", &rpcs3ps5_import_324},
    {"sceKernelGetCurrentCpu", &rpcs3ps5_import_325},
    {"sceKernelGetDirectMemorySize", &rpcs3ps5_import_326},
    {"sceKernelGetSystemSwVersion", &rpcs3ps5_import_327},
    {"sceKernelGetTscFrequency", &rpcs3ps5_import_328},
    {"sceKernelJitCreateAliasOfSharedMemory", &rpcs3ps5_import_329},
    {"sceKernelJitCreateSharedMemory", &rpcs3ps5_import_330},
    {"sceKernelJitMapSharedMemory", &rpcs3ps5_import_331},
    {"sceKernelMapDirectMemory", &rpcs3ps5_import_332},
    {"sceKernelMprotect", &rpcs3ps5_import_333},
    {"sceKernelMunmap", &rpcs3ps5_import_334},
    {"sceKernelReadTsc", &rpcs3ps5_import_335},
    {"sceKernelReleaseDirectMemory", &rpcs3ps5_import_336},
    {"sceKernelReserveVirtualRange", &rpcs3ps5_import_337},
    {"sceKernelUsleep", &rpcs3ps5_import_338},
    {"scePadInit", &rpcs3ps5_import_339},
    {"scePadOpen", &rpcs3ps5_import_340},
    {"scePadRead", &rpcs3ps5_import_341},
    {"scePadSetLightBar", &rpcs3ps5_import_342},
    {"scePadSetVibration", &rpcs3ps5_import_343},
    {"scePadSetVibrationMode", &rpcs3ps5_import_344},
    {"scePthreadGetaffinity", &rpcs3ps5_import_345},
    {"scePthreadSetaffinity", &rpcs3ps5_import_346},
    {"scePthreadYield", &rpcs3ps5_import_347},
    {"sceSystemServiceHideSplashScreen", &rpcs3ps5_import_348},
    {"sceSystemServiceLoadExec", &rpcs3ps5_import_349},
    {"sceUserServiceGetInitialUser", &rpcs3ps5_import_350},
    {"sceUserServiceInitialize", &rpcs3ps5_import_351},
    {"sceVideoOutConfigureOutput", &rpcs3ps5_import_352},
    {"sceVideoOutGetFlipStatus", &rpcs3ps5_import_353},
    {"sceVideoOutIsOutputSupported", &rpcs3ps5_import_354},
    {"sceVideoOutOpen", &rpcs3ps5_import_355},
    {"sceVideoOutRegisterBuffers2", &rpcs3ps5_import_356},
    {"sceVideoOutSetBufferAttribute2", &rpcs3ps5_import_357},
    {"sceVideoOutSetFlipRate", &rpcs3ps5_import_358},
    {"sceVideoOutSubmitFlip", &rpcs3ps5_import_359},
    {"sceVideoOutWaitVblank", &rpcs3ps5_import_360},
    {"sched_get_priority_max", &rpcs3ps5_import_361},
    {"sched_get_priority_min", &rpcs3ps5_import_362},
    {"select", &rpcs3ps5_import_363},
    {"sem_destroy", &rpcs3ps5_import_364},
    {"sem_init", &rpcs3ps5_import_365},
    {"sem_post", &rpcs3ps5_import_366},
    {"sem_wait", &rpcs3ps5_import_367},
    {"send", &rpcs3ps5_import_368},
    {"sendto", &rpcs3ps5_import_369},
    {"setjmp", &rpcs3ps5_import_370},
    {"setlocale", &rpcs3ps5_import_371},
    {"setrlimit", &rpcs3ps5_import_372},
    {"setsockopt", &rpcs3ps5_import_373},
    {"setvbuf", &rpcs3ps5_import_374},
    {"shm_open", &rpcs3ps5_import_375},
    {"shm_unlink", &rpcs3ps5_import_376},
    {"shutdown", &rpcs3ps5_import_377},
    {"sigaction", &rpcs3ps5_import_378},
    {"sigaddset", &rpcs3ps5_import_379},
    {"sigaltstack", &rpcs3ps5_import_380},
    {"sigdelset", &rpcs3ps5_import_381},
    {"sigemptyset", &rpcs3ps5_import_382},
    {"sigfillset", &rpcs3ps5_import_383},
    {"siglongjmp", &rpcs3ps5_import_384},
    {"sigprocmask", &rpcs3ps5_import_385},
    {"sigsetjmp", &rpcs3ps5_import_386},
    {"sin", &rpcs3ps5_import_387},
    {"sincos", &rpcs3ps5_import_388},
    {"sincosf", &rpcs3ps5_import_389},
    {"sinf", &rpcs3ps5_import_390},
    {"sinh", &rpcs3ps5_import_391},
    {"sinhf", &rpcs3ps5_import_392},
    {"snprintf", &rpcs3ps5_import_393},
    {"socket", &rpcs3ps5_import_394},
    {"sprintf", &rpcs3ps5_import_395},
    {"sqrt", &rpcs3ps5_import_396},
    {"sqrtf", &rpcs3ps5_import_397},
    {"srand", &rpcs3ps5_import_398},
    {"sscanf", &rpcs3ps5_import_399},
    {"stat", &rpcs3ps5_import_400},
    {"strcasecmp", &rpcs3ps5_import_401},
    {"strcat", &rpcs3ps5_import_402},
    {"strchr", &rpcs3ps5_import_403},
    {"strcmp", &rpcs3ps5_import_404},
    {"strcoll", &rpcs3ps5_import_405},
    {"strcpy", &rpcs3ps5_import_406},
    {"strcspn", &rpcs3ps5_import_407},
    {"strdup", &rpcs3ps5_import_408},
    {"strerror", &rpcs3ps5_import_409},
    {"strerror_r", &rpcs3ps5_import_410},
    {"strftime", &rpcs3ps5_import_411},
    {"strlen", &rpcs3ps5_import_412},
    {"strncasecmp", &rpcs3ps5_import_413},
    {"strncat", &rpcs3ps5_import_414},
    {"strncmp", &rpcs3ps5_import_415},
    {"strncpy", &rpcs3ps5_import_416},
    {"strndup", &rpcs3ps5_import_417},
    {"strnlen", &rpcs3ps5_import_418},
    {"strpbrk", &rpcs3ps5_import_419},
    {"strrchr", &rpcs3ps5_import_420},
    {"strspn", &rpcs3ps5_import_421},
    {"strstr", &rpcs3ps5_import_422},
    {"strtod", &rpcs3ps5_import_423},
    {"strtof", &rpcs3ps5_import_424},
    {"strtok", &rpcs3ps5_import_425},
    {"strtok_r", &rpcs3ps5_import_426},
    {"strtol", &rpcs3ps5_import_427},
    {"strtold", &rpcs3ps5_import_428},
    {"strtoll", &rpcs3ps5_import_429},
    {"strtoul", &rpcs3ps5_import_430},
    {"strtoull", &rpcs3ps5_import_431},
    {"strxfrm", &rpcs3ps5_import_432},
    {"swprintf", &rpcs3ps5_import_433},
    {"sync", &rpcs3ps5_import_434},
    {"sysconf", &rpcs3ps5_import_435},
    {"sysctl", &rpcs3ps5_import_436},
    {"sysctlbyname", &rpcs3ps5_import_437},
    {"syslog", &rpcs3ps5_import_438},
    {"system", &rpcs3ps5_import_439},
    {"tan", &rpcs3ps5_import_440},
    {"tanf", &rpcs3ps5_import_441},
    {"tanh", &rpcs3ps5_import_442},
    {"tanhf", &rpcs3ps5_import_443},
    {"time", &rpcs3ps5_import_444},
    {"tolower", &rpcs3ps5_import_445},
    {"toupper", &rpcs3ps5_import_446},
    {"towlower", &rpcs3ps5_import_447},
    {"towupper", &rpcs3ps5_import_448},
    {"trunc", &rpcs3ps5_import_449},
    {"truncate", &rpcs3ps5_import_450},
    {"truncf", &rpcs3ps5_import_451},
    {"tzset", &rpcs3ps5_import_452},
    {"ungetc", &rpcs3ps5_import_453},
    {"ungetwc", &rpcs3ps5_import_454},
    {"unlink", &rpcs3ps5_import_455},
    {"usleep", &rpcs3ps5_import_456},
    {"utime", &rpcs3ps5_import_457},
    {"utimes", &rpcs3ps5_import_458},
    {"vasprintf", &rpcs3ps5_import_459},
    {"vfprintf", &rpcs3ps5_import_460},
    {"vsnprintf", &rpcs3ps5_import_461},
    {"vsprintf", &rpcs3ps5_import_462},
    {"vsscanf", &rpcs3ps5_import_463},
    {"wait", &rpcs3ps5_import_464},
    {"wcrtomb", &rpcs3ps5_import_465},
    {"wcscoll", &rpcs3ps5_import_466},
    {"wcslen", &rpcs3ps5_import_467},
    {"wcstod", &rpcs3ps5_import_468},
    {"wcstof", &rpcs3ps5_import_469},
    {"wcstol", &rpcs3ps5_import_470},
    {"wcstold", &rpcs3ps5_import_471},
    {"wcstoll", &rpcs3ps5_import_472},
    {"wcstoul", &rpcs3ps5_import_473},
    {"wcstoull", &rpcs3ps5_import_474},
    {"wcsxfrm", &rpcs3ps5_import_475},
    {"wctob", &rpcs3ps5_import_476},
    {"wctype", &rpcs3ps5_import_477},
    {"wmemchr", &rpcs3ps5_import_478},
    {"wmemcmp", &rpcs3ps5_import_479},
    {"write", &rpcs3ps5_import_480},
    {"writev", &rpcs3ps5_import_481},
};

void rpcs3ps5_import_check(void)
{
    const size_t count = sizeof(g_imports) / sizeof(g_imports[0]);
    size_t missing = 0;
    for (size_t i = 0; i < count; i++) {
        if (!g_imports[i].address) {
            rpcs3ps5_boot_log("import: MISSING %s", g_imports[i].name);
            missing++;
        }
    }
    rpcs3ps5_boot_log("import: %zu of %zu imports resolved, %zu missing", count - missing, count, missing);
}
