#!/usr/bin/env bash
# Regenerate app/ps5/src/import_check.c from the last linked title: every symbol the title
# imports from the SDK's system-module stubs, checked for NULL at startup (see the file).
# Run after a title link that changed the import set:  port/gen-import-check.sh && tools/vm-build-app.sh
set -euo pipefail
here=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
limactl shell ps5build -- bash -s <<'VM'
set -euo pipefail
SDK=~/work/ps5-rpcs3-app/.deps/native/ps5-payload-sdk
cd ~/work/ps5-rpcs3-app/build/ps5/link
mkdir -p /tmp/imp
for f in $SDK/target/lib/*.so; do llvm-nm -D --defined-only "$f" 2>/dev/null | awk '{print $3}'; done | sort -u > /tmp/imp/stubnames.txt
llvm-nm -u llvm-pie.elf | awk '{print $2}' | grep -E '^[A-Za-z_][A-Za-z0-9_]*$' \
  | grep -vxE 'getenv|setenv|unsetenv|putenv' | sort -u > /tmp/imp/imports.txt
comm -12 /tmp/imp/imports.txt /tmp/imp/stubnames.txt > /tmp/imp/real.txt
python3 - <<'PY'
names = open("/tmp/imp/real.txt").read().split()
out = ["/*",
       " * RPCS3 PS5 - import self-check (generated by port/gen-import-check.sh from the linked title).",
       " *",
       " * The console leaves a title import pointing at nothing when no module gives it to titles.",
       " * rpcs3ps5_import_check() runs from the first constructor and writes every import that",
       " * resolved to NULL to /app0/rpcs3/ps5-boot.log, so one launch lists them all.",
       " * SPDX-License-Identifier: GPL-3.0-or-later",
       " */",
       "#include <stddef.h>", "", "void rpcs3ps5_boot_log(const char *format, ...);", ""]
out += ['extern char rpcs3ps5_import_%d __asm__("%s") __attribute__((weak));' % (i, n) for i, n in enumerate(names)]
out += ["", "static const struct { const char *name; const void *address; } g_imports[] = {"]
out += ['    {"%s", &rpcs3ps5_import_%d},' % (n, i) for i, n in enumerate(names)]
out += ["};", "", """void rpcs3ps5_import_check(void)
{
    const size_t count = sizeof(g_imports) / sizeof(g_imports[0]);
    size_t missing = 0;
    for (size_t i = 0; i < count; i++) {
        if (!g_imports[i].address) {
            rpcs3ps5_boot_log("import: MISSING %s", g_imports[i].name);
            missing++;
        }
    }
    rpcs3ps5_boot_log("import: %zu of %zu imports resolved, %zu missing", count - missing, count, missing);
}"""]
open("/tmp/imp/import_check.c", "w").write("\n".join(out) + "\n")
print(len(names), "imports")
PY
VM
limactl copy ps5build:/tmp/imp/import_check.c "$here/app/ps5/src/import_check.c"
